apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault-internal.azdevopsb82.online:8200"
      path: "roboshop-dev"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"

