name: Apply - Terraform
on: workflow_dispatch
jobs:
  terraform:
    uses: raghudevopsb82/github-reusable-actions/.github/workflows/terraform.yml@main
    with:
      action: apply
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
