name: Apply - Terraform
on: workflow_dispatch
jobs:
    apply:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v4

        - name: Retrieve Vault Secrets
          id: import-secrets
          uses: hashicorp/vault-action@v2
          with:
            url: http://vault.azdevopsb82.online:8200
            token: ${{ secrets.VAULT_TOKEN }}
            secrets: |
              infra/data/github-actions/ARM_CLIENT_ID | ARM_CLIENT_ID ;
              infra/data/github-actions/ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
              infra/data/github-actions/ARM_SUBSCRIPTION_ID | ARM_SUBSCRIPTION_ID ;
              infra/data/github-actions/ARM_TENANT_ID | ARM_TENANT_ID ;
          env:
            vault_token: ${{ secrets.VAULT_TOKEN }}

        - run: make dev-apply vault_token=${vault_token}
          env:
            vault_token: ${{ secrets.VAULT_TOKEN }}


